
image: docker:latest

stages:
  - production

production:
  stage: production
  script:
    - docker login -u daero -p 
    - docker build --tag Daero/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
    - docker push Daero/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA