
image: docker:latest

stages:
  - production

production:
  stage: production
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build --tag $DOCKER_USERNAME/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USERNAME/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA