
image: docker:latest

stages:
  - production
 
production:
  stage: production
  script:
    - docker build --tag $K8S_SECRET_DOCKER_USERNAME/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
    - docker login -u $K8S_SECRET_DOCKER_USERNAME --password-stdin $K8S_SECRET_DOCKER_PASSWORD
    - docker push $K8S_SECRET_DOCKER_USERNAME/warm-images:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA